CREATE TABLE IF NOT EXISTS bldg_com (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    bldg_num VARCHAR(255),
    bldg_category VARCHAR(255),
    bldg_type VARCHAR(255),
    ground_floor_area VARCHAR(255),
    com_ext_wall_type VARCHAR(255),
    com_stories_code VARCHAR(255),
    year_built VARCHAR(255),
    com_const_type VARCHAR(255),
    tot_apts VARCHAR(255),
    nbr_of_apts_eff VARCHAR(255),
    nbr_of_apts_1br VARCHAR(255),
    nbr_of_apts_2br VARCHAR(255),
    nbr_of_apts_3br VARCHAR(255),
    nbr_of_apts_other VARCHAR(255),
    first_date VARCHAR(255),
    last_date VARCHAR(255),
    last_update VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS bldg_res (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    bldg_num VARCHAR(255),
    res_occ_type VARCHAR(255),
    bsmt_type VARCHAR(255),
    bsmt_finish_type VARCHAR(255),
    bsmt_area_finished VARCHAR(255),
    bsmt_area_partial VARCHAR(255),
    res_ext_wall_type VARCHAR(255),
    living_area_total VARCHAR(255),
    living_area_at_grade VARCHAR(255),
    lving_area_up_down VARCHAR(255),
    room_area VARCHAR(255),
    res_stories_code VARCHAR(255),
    full_baths VARCHAR(255),
    half_baths VARCHAR(255),
    air_cond_central VARCHAR(255),
    air_cond_window VARCHAR(255),
    central_heating VARCHAR(255),
    attic VARCHAR(255),
    garage_1 VARCHAR(255),
    garage_2 VARCHAR(255),
    carport_1 VARCHAR(255),
    carport_2 VARCHAR(255),
    year_built VARCHAR(255),
    res_model_code VARCHAR(255),
    res_model_adj_code VARCHAR(255),
    effective_year_built VARCHAR(255),
    functional_dep VARCHAR(255),
    locational_dep VARCHAR(255),
    first_date VARCHAR(255),
    last_date VARCHAR(255),
    last_update VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS bldg_res_imp (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    bldg_num VARCHAR(255),
    imp_num VARCHAR(255),
    imp_code VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS bldg_sect (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    bldg_num VARCHAR(255),
    sect_num VARCHAR(255),
    sect_category VARCHAR(255),
    sect_type VARCHAR(255),
    framing_type VARCHAR(255),
    excav_type VARCHAR(255),
    ext_wall_type VARCHAR(255),
    level_from VARCHAR(255),
    level_to VARCHAR(255),
    story_height VARCHAR(255),
    area VARCHAR(255),
    foundation_type VARCHAR(255),
    roof_type VARCHAR(255),
    roof_const_1 VARCHAR(255),
    roof_const_2 VARCHAR(255),
    roof_const_3 VARCHAR(255),
    roof_const_4 VARCHAR(255),
    heating VARCHAR(255),
    air_cond_central VARCHAR(255),
    air_cond_window VARCHAR(255),
    electricity VARCHAR(255),
    fire_protection VARCHAR(255),
    elevator VARCHAR(255),
    bsmt_story_height VARCHAR(255),
    bsmt_nbr_of_stories VARCHAR(255),
    bsmt_area_finished VARCHAR(255),
    bsmt_area_unfinished VARCHAR(255),
    bsmt_garage_area VARCHAR(255),
    first_date VARCHAR(255),
    last_date VARCHAR(255),
    last_update VARCHAR(255)
)