CREATE TABLE IF NOT EXISTS staging_2.bldg_com (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    bldg_num VARCHAR(255),
    bldg_category VARCHAR(255),
    bldg_type VARCHAR(255),
    ground_floor_area VARCHAR(255),
    com_ext_wall_type VARCHAR(255),
    com_stories_code VARCHAR(255),
    year_built VARCHAR(255),
    com_const_type VARCHAR(255),
    tot_apts VARCHAR(255),
    nbr_of_apts_eff VARCHAR(255),
    nbr_of_apts_1br VARCHAR(255),
    nbr_of_apts_2br VARCHAR(255),
    nbr_of_apts_3br VARCHAR(255),
    nbr_of_apts_other VARCHAR(255),
    first_date VARCHAR(255),
    last_date VARCHAR(255),
    last_update VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.bldg_res (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    bldg_num VARCHAR(255),
    res_occ_type VARCHAR(255),
    bsmt_type VARCHAR(255),
    bsmt_finish_type VARCHAR(255),
    bsmt_area_finished VARCHAR(255),
    bsmt_area_partial VARCHAR(255),
    res_ext_wall_type VARCHAR(255),
    living_area_total VARCHAR(255),
    living_area_at_grade VARCHAR(255),
    lving_area_up_down VARCHAR(255),
    room_area VARCHAR(255),
    res_stories_code VARCHAR(255),
    full_baths VARCHAR(255),
    half_baths VARCHAR(255),
    air_cond_central VARCHAR(255),
    air_cond_window VARCHAR(255),
    central_heating VARCHAR(255),
    attic VARCHAR(255),
    garage_1 VARCHAR(255),
    garage_2 VARCHAR(255),
    carport_1 VARCHAR(255),
    carport_2 VARCHAR(255),
    year_built VARCHAR(255),
    res_model_code VARCHAR(255),
    res_model_adj_code VARCHAR(255),
    effective_year_built VARCHAR(255),
    functional_dep VARCHAR(255),
    locational_dep VARCHAR(255),
    first_date VARCHAR(255),
    last_date VARCHAR(255),
    last_update VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.bldg_res_imp (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    bldg_num VARCHAR(255),
    imp_num VARCHAR(255),
    imp_code VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.bldg_sect (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    bldg_num VARCHAR(255),
    sect_num VARCHAR(255),
    sect_category VARCHAR(255),
    sect_type VARCHAR(255),
    framing_type VARCHAR(255),
    excav_type VARCHAR(255),
    ext_wall_type VARCHAR(255),
    level_from VARCHAR(255),
    level_to VARCHAR(255),
    story_height VARCHAR(255),
    area VARCHAR(255),
    foundation_type VARCHAR(255),
    roof_type VARCHAR(255),
    roof_const_1 VARCHAR(255),
    roof_const_2 VARCHAR(255),
    roof_const_3 VARCHAR(255),
    roof_const_4 VARCHAR(255),
    heating VARCHAR(255),
    air_cond_central VARCHAR(255),
    air_cond_window VARCHAR(255),
    electricity VARCHAR(255),
    fire_protection VARCHAR(255),
    elevator VARCHAR(255),
    bsmt_story_height VARCHAR(255),
    bsmt_nbr_of_stories VARCHAR(255),
    bsmt_area_finished VARCHAR(255),
    bsmt_area_unfinished VARCHAR(255),
    bsmt_garage_area VARCHAR(255),
    first_date VARCHAR(255),
    last_date VARCHAR(255),
    last_update VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.cd_attr_type_num (
    attr_type VARCHAR(255),
    attr_num VARCHAR(255),
    pda_num VARCHAR(255),
    pda_alpha VARCHAR(255),
    name VARCHAR(255),
    ignore_code VARCHAR(255),
    expire_date VARCHAR(255),
    board_bill_status VARCHAR(255),
    first_board_bill_num VARCHAR(255),
    first_ord_num VARCHAR(255),
    first_effect_date VARCHAR(255),
    last_board_bill_num VARCHAR(255),
    last_ord_num VARCHAR(255),
    last_effect_date VARCHAR(255),
    note VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.cx_prcl_cn_blk_10 (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    cens_tract_10 VARCHAR(255),
    cens_block_10 VARCHAR(255),
    is_primary_cens_blk_10 VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.prcl (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    parcel_id VARCHAR(255),
    prim_addr_rec_num VARCHAR(255),
    addr_type VARCHAR(255),
    low_addr_num VARCHAR(255),
    low_addr_suf VARCHAR(255),
    high_addr_num VARCHAR(255),
    high_addr_suf VARCHAR(255),
    nlc VARCHAR(255),
    parity VARCHAR(255),
    st_pre_dir VARCHAR(255),
    st_name VARCHAR(255),
    st_type VARCHAR(255),
    st_suf_dir VARCHAR(255),
    std_unit_num VARCHAR(255),
    owner_name VARCHAR(255),
    owner_name_2 VARCHAR(255),
    owner_addr VARCHAR(255),
    owner_city VARCHAR(255),
    owner_state VARCHAR(255),
    owner_country VARCHAR(255),
    owner_zip VARCHAR(255),
    owner_rank VARCHAR(255),
    legal_desc_1 VARCHAR(255),
    legal_desc_2 VARCHAR(255),
    legal_desc_3 VARCHAR(255),
    legal_desc_4 VARCHAR(255),
    legal_desc_5 VARCHAR(255),
    asr_class_code VARCHAR(255),
    asr_land_use_1 VARCHAR(255),
    asr_land_use_2 VARCHAR(255),
    redev_phase VARCHAR(255),
    redev_year_end VARCHAR(255),
    redev_phase_2 VARCHAR(255),
    redev_year_end_2 VARCHAR(255),
    vacant_lot VARCHAR(255),
    spec_bus_dist VARCHAR(255),
    spec_bus_dist_2 VARCHAR(255),
    tif_dist VARCHAR(255),
    lending_agcy VARCHAR(255),
    condominium VARCHAR(255),
    nbr_of_units VARCHAR(255),
    nbr_of_apts VARCHAR(255),
    frontage VARCHAR(255),
    land_area VARCHAR(255),
    rec_daily_date VARCHAR(255),
    rec_book_num VARCHAR(255),
    rec_page_num VARCHAR(255),
    asd_land VARCHAR(255),
    asd_improve VARCHAR(255),
    asd_total VARCHAR(255),
    bill_land VARCHAR(255),
    bill_improve VARCHAR(255),
    bill_total VARCHAR(255),
    apr_land VARCHAR(255),
    cost_apr_improve VARCHAR(255),
    asmt_appeal_year VARCHAR(255),
    asmt_appeal_num VARCHAR(255),
    asmt_appeal_type VARCHAR(255),
    prior_asd_date VARCHAR(255),
    prior_asd_land VARCHAR(255),
    prior_asd_total VARCHAR(255),
    prior_tax_amt VARCHAR(255),
    cda_land_use_1 VARCHAR(255),
    cda_land_use_2 VARCHAR(255),
    lrms_unit_num VARCHAR(255),
    zoning VARCHAR(255),
    nbr_of_bldgs_res VARCHAR(255),
    nbr_of_bldgs_com VARCHAR(255),
    first_year_built VARCHAR(255),
    last_year_built VARCHAR(255),
    res_sales_price VARCHAR(255),
    res_sales_date VARCHAR(255),
    vac_bldg_year VARCHAR(255),
    geo_city_block_part VARCHAR(255),
    ward_10 VARCHAR(255),
    precinct_10 VARCHAR(255),
    insp_area_10 VARCHAR(255),
    ward_00 VARCHAR(255),
    precinct_02 VARCHAR(255),
    precinct_04 VARCHAR(255),
    nbrhd VARCHAR(255),
    cda_dist VARCHAR(255),
    cda_sub_dist VARCHAR(255),
    police_dist VARCHAR(255),
    cens_tract_10 VARCHAR(255),
    cens_block_10 VARCHAR(255),
    cens_block_00 VARCHAR(255),
    ward_90 VARCHAR(255),
    precinct_90 VARCHAR(255),
    house_cons_dist VARCHAR(255),
    asr_nbrhd VARCHAR(255),
    ent_zone VARCHAR(255),
    impact_area VARCHAR(255),
    ctd_area VARCHAR(255),
    leaf_area VARCHAR(255),
    zip VARCHAR(255),
    on_flood_block VARCHAR(255),
    spec_parcel_type VARCHAR(255),
    sub_parcel_type VARCHAR(255),
    nbr_of_sub_accts VARCHAR(255),
    nbr_of_condos VARCHAR(255),
    lrms_parcel VARCHAR(255),
    acct_primary VARCHAR(255),
    gis_primary VARCHAR(255),
    gis_city_block VARCHAR(255),
    gis_parcel VARCHAR(255),
    gis_owner_code VARCHAR(255),
    handle VARCHAR(255),
    parcel_9 VARCHAR(255),
    first_date VARCHAR(255),
    last_date VARCHAR(255),
    owner_update VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.prcl_addr (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    lrmsnlc VARCHAR(255),
    double_blk_code VARCHAR(255),
    low_addr_num VARCHAR(255),
    low_addr_suf VARCHAR(255),
    high_addr_num VARCHAR(255),
    high_addr_suf VARCHAR(255),
    unit_num VARCHAR(255),
    addr_type VARCHAR(255),
    rec_num VARCHAR(255),
    rec_num_lrms VARCHAR(255),
    nlc VARCHAR(255),
    parity VARCHAR(255),
    st_pre_dir VARCHAR(255),
    st_name VARCHAR(255),
    st_type VARCHAR(255),
    st_suf_dir VARCHAR(255),
    std_unit_adjd VARCHAR(255),
    low_hfr_unit_mask VARCHAR(255),
    high_hfr_unit_mask VARCHAR(255),
    zip VARCHAR(255),
    primary_addr VARCHAR(255),
    lrms_primary_addr VARCHAR(255),
    is_lrms_primary VARCHAR(255),
    rank VARCHAR(255),
    first_date VARCHAR(255),
    last_date VARCHAR(255),
    last_update VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.prcl_addr_lrms (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    lrms_nlc VARCHAR(255),
    double_blk_code VARCHAR(255),
    addr_num VARCHAR(255),
    addr_suf VARCHAR(255),
    addr_type VARCHAR(255),
    rec_num VARCHAR(255),
    lrms_primary_addr VARCHAR(255),
    nlc VARCHAR(255),
    parity VARCHAR(255),
    low_addr_num VARCHAR(255),
    low_addr_suf VARCHAR(255),
    high_addr_num VARCHAR(255),
    high_addr_suf VARCHAR(255),
    st_pre_dir VARCHAR(255),
    st_name VARCHAR(255),
    st_type VARCHAR(255),
    st_suf_dir VARCHAR(255),
    rank VARCHAR(255),
    first_date VARCHAR(255),
    last_date VARCHAR(255),
    last_update VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.prcl_asmt (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    asr_class_code VARCHAR(255),
    asd_land VARCHAR(255),
    asd_improve VARCHAR(255),
    asd_total VARCHAR(255),
    bill_land VARCHAR(255),
    bill_improve VARCHAR(255),
    bill_total VARCHAR(255),
    apr_land VARCHAR(255),
    cost_apr_improve VARCHAR(255),
    asr_land_use VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.prcl_attr (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    attr_type VARCHAR(255),
    attr_num VARCHAR(255),
    last_update VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.prcl_date (
    last_update VARCHAR(255),
    status VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.prcl_imp (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    imp_num VARCHAR(255),
    imp_code VARCHAR(255),
    imp_measure VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.prcl_rear (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    bill_year VARCHAR(255),
    bill_suffix VARCHAR(255),
    last_update VARCHAR(255),
    original_charge VARCHAR(255),
    tax_amt VARCHAR(255),
    land_value VARCHAR(255),
    improve_value VARCHAR(255),
    total_value VARCHAR(255),
    tax_bal VARCHAR(255),
    nbr_of_sewer_lines VARCHAR(255),
    is_add VARCHAR(255),
    is_deleted VARCHAR(255),
    is_paid_under_protest VARCHAR(255),
    is_prior VARCHAR(255),
    com_res_code VARCHAR(255),
    spec_bus_dis VARCHAR(255),
    sewer_line_split VARCHAR(255),
    res_tax_amt VARCHAR(255),
    com_land_value VARCHAR(255),
    com_improve_value VARCHAR(255),
    com_total_value VARCHAR(255),
    com_tax_amt VARCHAR(255),
    sur_tax_amt VARCHAR(255),
    sbd_tax_amt VARCHAR(255),
    lat_sewer_amt VARCHAR(255),
    demo_charge VARCHAR(255),
    nuisance_tax VARCHAR(255),
    tif_dist VARCHAR(255),
    tif_split VARCHAR(255),
    spec_bus_dist_2 VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.prcl_sbd (
    city_block VARCHAR(255),
    parcel VARCHAR(255),
    owner_code VARCHAR(255),
    sbd_num VARCHAR(255),
    sbd_rec_num VARCHAR(255),
    sbd_type VARCHAR(255),
    sbd_amount VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staging_2.dead_parcels (
    parcel_id VARCHAR(255),
    date VARCHAR(255)
)